sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
install: pip install -r requirements/dev.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/autoapp.py"
  - export FLASK_DEBUG=1
  - export DATABASE_URL="postgres://kwrjrruroljjcc:44becbac21b3e14d22454e3fc162b0c4dfa9241d7a2daf3a539be8d3ab5513fc@ec2-54-235-66-24.compute-1.amazonaws.com:5432/ddfmu0dhuo06bq"
  - export CONFIG_ENV="prod"

script:
  - python manage.py test