"""empty message

Revision ID: 719bf03db192
Revises: 4cd0a0bafd5d
Create Date: 2018-10-27 08:05:59.780489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719bf03db192'
down_revision = '4cd0a0bafd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_user_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('no_of_likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'no_of_likes')
    op.drop_table('post_user_likes')
    # ### end Alembic commands ###
